### ISSUE TITLE
PushMessageAsync to roomId

### ISSUE THREAD

**Issue by marrrschine** [pierre3/LineMessagingApi#29]
Hi guys, great work, thats for that project!

I have a question (not an issue) regarding the ```PushMessageAsync```.
As of now I do

```
        public async void SendMessage(string m)
        {
            await Client.PushMessageAsync("Uyxyxy", m);
        }
```
where ```Uyxyxy``` is a userId. That is working! In the LineMessagingClient definition I can see 
```
        // Summary:
        //     Send text messages to a user, group, or room at any time. Note: Use of push messages
        //     are limited to certain plans.
```
So now I want to send a message to a room. Do you know where I get the roomId from? 
From the [LINE developer API](https://developers.line.me/en/docs/messaging-api/reference/#send-push-message) reference I can see that the Request body property ```to``` hast to be the

> ID of the target recipient. Use a userId, groupId, or roomId value returned in a webhook event object. Do not use the LINE ID found on the LINE app.

Does that mean I have to deal with webhook event objects? Or is there any other way? Do you have experience with that? And maybe an example? Thanks a lot in advance.

**Comment by pierre3** [comment]
Hi marrrschine, I'm glad you brought that up!

In the API reference, "Common properties" "Source User", "Source Group", "Source Room" are defined.

https://developers.line.me/en/docs/messaging-api/reference/#common-properties

But, in this library it is unified to the WebhookEventSource class.

```cs
public class WebhookEventSource
{
        public EventSourceType Type { get; }

        /// <summary>
        /// User, Group or Room Id
        /// </summary>
        public string Id { get; }

        /// <summary>
        /// UserId of the Group or Room
        /// </summary>
        public string UserId { get; }
}
```
If EventSource.Type is User then EventSource.Id is UserId.
If EventSource.Type is Group then EventSource.Id is GroupId.
If EventSource.Type is Room then EventSource.Id is RoomId.

```cs
switch (webhookEvent.Type)
{
    case EventSourceType.User:
        var userId = webhookEvent.Source.Id;
        await client.PushMessageAsync(userId, "Message to user");
        break;
    case EventSourceType.Group:
        var groupId = webhookEvent.Source.Id;
        await client.PushMessageAsync(groupId, "Message to group");
        break;
    case EventSourceType.Room:
        var roomId = webhookEvent.Source.Id;
        await client.PushMessageAsync(roomId, "Message to room");
        break;
}
```

**Comment by marrrschine** [comment]
Thanks for your reply. 
So that means I have to write and - due to https requirement - publish an app to retrieve the webhook events? Would be much easier if I could do that using the LINE developers console...

**Comment by pierre3** [comment]
It is possible to send messages from [LINE＠Manager](https://admin-official.line.me/
) to all users. However, it seems that it can not be sent to a group or a talk room.

We have a template (using Visual Studio 2017) that makes it easy to create a bot application on Windows Azure .
- https://marketplace.visualstudio.com/items?itemName=pierre3.LINEBotCSharpTemplate

Please try creating a bot application that can handle Webhook events.

**Comment by marrrschine** [comment]
Ok! Thanks again! :+1:
