### ISSUE TITLE
There seems to be an error in LineBotApp.cs.

### ISSUE THREAD

**Issue by kaki104** [pierre3/LineMessagingApi#30]
Hi
I have found two places where errors can occur.
1. 325 Line
                            for (int i = 0; i < (double)hcard.Buttons.Count / 4; i++)
If the button does not exist, an error occurs because it is null.

2. 343 Line
var actionLabel = hcard.Title?.Length < hcard.Subtitle?.Length ? hcard.Title : hcard.Subtitle;
If the subtitle does not exist, an error occurs because the comparison is not possible.

Please check the source code.

Thank you very much for making a good source and publishing it. This time I use your source to make PPT and video about how to use DirectLine and Line Message API. I will notify you after posting your blog post later.

Best regards,
Park

**Comment by kenakamu** [comment]
Thanks Park, 

I agree with you from code perspective, but I don't know the scenario what Hero card doesn't have title nor subtitle or no buttons at all. If you can give me good sample, i am happy to fix it, then the issue is that LINE side requires these properties so we have to made up something.

**Comment by kaki104** [comment]
@kenakamu 

I wrote a post about how to connect Bot Framework and Line Messenger for developers.
And, the simple bot created at this time provides only some information of the hero card.
https://github.com/kaki104/bot/blob/master/Sample2/HelloWorldBot/Dialogs/DirectLineBotDialog.cs

Do I only have to use a hero card with titles, subtitles, and buttons?

**Comment by kenakamu** [comment]
The issue comes from differences between bot builder and api messaging that somebody fileds are mandatory on one side yet not another.  

In that case we need to be smart to find workaround. We can use text property from message level for example

**Comment by kenakamu** [comment]
@kaki104 

The easiest way is to let HeroCard has text at least. It is LINE's requirements to have these fields. If you don't we have to assign something to required field. Please give your thoughts and the post URL.

**Comment by kaki104** [comment]
The reason why I created an issue is that Bot Framework does not have a required entry when creating a HeroCard and no error when connecting to another messenger.
However, if Title, SubTitle, and Buttons are required in LINE Messenger, I will modify my Bot.

Finally, a post about how to link Bot Framework and LINE Messenger will be posted in early April.

Thank you so much @kenakamu

**Comment by kaki104** [comment]
You just completed the posting titled "Connecting with LINE Messenger using Direct Line".
http://kaki104.tistory.com/579
