### ISSUE TITLE
Can not push flex message

### ISSUE THREAD

**Issue by MengSung** [pierre3/LineMessagingApi#37]
Push Flex Message got error
--------------
                aFlexMessage = new FlexMessage("Restrant")
                {
                    
                    Container = new BubbleContainer()
                    {
                        Hero = new ImageComponent(url: "https://scdn.line-apps.com/n/channel_devcenter/img/fx/01_1_cafe.png")
                        {
                            
                            Size = ComponentSize.Full,
                            AspectRatio = AspectRatio._20_13,
                            AspectMode = AspectMode.Cover,
                            Action = new UriTemplateAction(null, "http://linecorp.com/")
                        },
                        Body = new BoxComponent(layout: BoxLayout.Vertical)
                        {
                            Contents = new IFlexComponent[] {
                        new TextComponent("Broun Cafe")
                        {
                            Weight = Weight.Bold,
                            Size = ComponentSize.Xl
                        },
                        new BoxComponent(layout: BoxLayout.Baseline)
                        {
                            Margin = Spacing.Md,
                            Contents = new IFlexComponent[]
                            {
                                new IconComponent("https://scdn.line-apps.com/n/channel_devcenter/img/fx/review_gold_star_28.png")
                                {
                                    Size = ComponentSize.Sm
                                },
                                new IconComponent("https://scdn.line-apps.com/n/channel_devcenter/img/fx/review_gold_star_28.png")
                                {
                                    Size = ComponentSize.Sm
                                },
                                new IconComponent("https://scdn.line-apps.com/n/channel_devcenter/img/fx/review_gold_star_28.png")
                                {
                                    Size = ComponentSize.Sm
                                },
                                new IconComponent("https://scdn.line-apps.com/n/channel_devcenter/img/fx/review_gold_star_28.png")
                                {
                                    Size = ComponentSize.Sm
                                },
                                new IconComponent("https://scdn.line-apps.com/n/channel_devcenter/img/fx/review_gray_star_28.png")
                                {
                                    Size = ComponentSize.Sm
                                },
                                new TextComponent("4.0")
                                {
                                    Size = ComponentSize.Sm,
                                    Margin = Spacing.Md,
                                    Flex = 0,
                                    Color = "#999999"
                                }
                            }
                        },
                        new BoxComponent(BoxLayout.Vertical)
                        {
                            Margin = Spacing.Lg,
                            Spacing = Spacing.Sm,
                            Contents = new IFlexComponent[]
                            {
                                new BoxComponent(BoxLayout.Baseline)
                                {
                                    Spacing = Spacing.Sm,
                                    Contents = new IFlexComponent[]
                                    {
                                        new TextComponent("Place")
                                        {
                                            Size = ComponentSize.Sm,
                                            Color = "#aaaaaa",
                                            Flex = 1
                                        },
                                        new TextComponent("Miraina Tower, 4-1-6 Shinjuku, Tokyo")
                                        {
                                            Size = ComponentSize.Sm,
                                            Wrap = true,
                                            Color = "#666666",
                                            Flex = 5
                                        }
                                    }
                                }
                            }
                        },
                        new BoxComponent(BoxLayout.Baseline)
                        {
                            Spacing = Spacing.Sm,
                            Contents = new IFlexComponent[]
                            {
                                new TextComponent("Time")
                                {
                                    Size = ComponentSize.Sm,
                                    Color = "#aaaaaa",
                                    Flex = 1
                                },
                                new TextComponent("10:00 - 23:00")
                                {
                                    Size = ComponentSize.Sm,
                                    Wrap = true,
                                    Color = "#666666",
                                    Flex=5
                                }
                            }
                        }
                    }
                        },
                        Footer = new BoxComponent(BoxLayout.Vertical)
                        {
                            Spacing = Spacing.Sm,
                            Flex = 0,
                            Contents = new IFlexComponent[]
        {
                        new ButtonComponent(new UriTemplateAction("Call", "https://linecorp.com"))
                        {
                            Style = ButtonStyle.Link,
                            Height = ButtonHeight.Sm
                        },
                        new ButtonComponent(new UriTemplateAction("WEBSITE", "https://linecorp.com"))
                        {
                            Style = ButtonStyle.Link,
                            Height = ButtonHeight.Sm
                        },
                        new SpacerComponent(ComponentSize.Sm)
        }
                        }
                    }
                };

                json = JsonConvert.SerializeObject(aFlexMessage);

                await m_PushUtility.SendMessage(DisplayLineId, new List<ISendMessage> { aFlexMessage });
===============================================
ERROR MESSAGE :
MESSAGE = ERROR : FullName = LineApiWebhook.LineBotApp , Time = 2018/9/11 下午 08:07:36 , Description = StatusCode=BadRequest, The request body has 1 error(s),[{May not be empty, messages[0].contents}]

**Comment by pierre3** [comment]
Hi, ＠MengSung
Thank you for your feed back.

The property name of the FlexMessage object was wrong.
I fixed it (73abce2), please try again.

**Comment by MengSung** [comment]
You did good job, many thanks. However, could you also provide carsoul sample?

**Comment by pierre3** [comment]
You can create a carousel message as follows.

```cs
var bubble01 = new BubbleContainer()
{
    //...
};
var bubble02 = new BubbleContainer()
{
    //...
};

//Sets the "CarouselContainer" object to the "Contents" property.
var caroucel = new FlexMessage("Caroucel Message")
{
    Contents = new CarouselContainer()
    {
        Contents = new[] { bubble01, bubble02}
    }
};

//(Another way) 
//Uses the "CreateCarouselMessage" static method and the "AddBubbleContainer" extension method.            
caroucel = FlexMessage.CreateCarouselMessage("Caroucel Message")                
    .AddBubbleContainer(bubble01)
    .AddBubbleContainer(bubble02);
            
```
