### ISSUE TITLE
IssueChannelAccessTokenAsync causes NullReferenceException

### ISSUE THREAD

**Issue by pinkplus** [pierre3/LineMessagingApi#39]
I'm trying to issue a short-time channel access token before I start to use the API. I found that if I call `IssueChannelAccessTokenAsync` before calling `LineMessagingClient` constructor, I'll get a NRE, probably because `IssueChannelAccessTokenAsync` needs to access `_url` static field which is set by the constructor. Without the constructor being called first, I can't issue a short-time channel access.

**Comment by pierre3** [comment]
Thank you for your feedback.
I have released a modified version. 

https://github.com/pierre3/LineMessagingApi/releases/tag/Release_1.4.2

**Comment by pinkplus** [comment]
Thanks!
